// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteTarget.Infrastructure.Data;

#nullable disable

namespace TesteTarget.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003210240_AdicionarVendas")]
    partial class AdicionarVendas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TesteTarget.Domain.Comissoes.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Vendedor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Venda", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Valor = 1200.50m,
                            Vendedor = "João Silva"
                        },
                        new
                        {
                            Id = 2,
                            Valor = 950.75m,
                            Vendedor = "João Silva"
                        },
                        new
                        {
                            Id = 3,
                            Valor = 1800.00m,
                            Vendedor = "João Silva"
                        },
                        new
                        {
                            Id = 4,
                            Valor = 1400.30m,
                            Vendedor = "João Silva"
                        },
                        new
                        {
                            Id = 5,
                            Valor = 1100.90m,
                            Vendedor = "João Silva"
                        },
                        new
                        {
                            Id = 6,
                            Valor = 1550.00m,
                            Vendedor = "João Silva"
                        },
                        new
                        {
                            Id = 7,
                            Valor = 1700.80m,
                            Vendedor = "João Silva"
                        },
                        new
                        {
                            Id = 8,
                            Valor = 250.30m,
                            Vendedor = "João Silva"
                        },
                        new
                        {
                            Id = 9,
                            Valor = 480.75m,
                            Vendedor = "João Silva"
                        },
                        new
                        {
                            Id = 10,
                            Valor = 320.40m,
                            Vendedor = "João Silva"
                        },
                        new
                        {
                            Id = 11,
                            Valor = 2100.40m,
                            Vendedor = "Maria Souza"
                        },
                        new
                        {
                            Id = 12,
                            Valor = 1350.60m,
                            Vendedor = "Maria Souza"
                        },
                        new
                        {
                            Id = 13,
                            Valor = 950.20m,
                            Vendedor = "Maria Souza"
                        },
                        new
                        {
                            Id = 14,
                            Valor = 1600.75m,
                            Vendedor = "Maria Souza"
                        },
                        new
                        {
                            Id = 15,
                            Valor = 1750.00m,
                            Vendedor = "Maria Souza"
                        },
                        new
                        {
                            Id = 16,
                            Valor = 1450.90m,
                            Vendedor = "Maria Souza"
                        },
                        new
                        {
                            Id = 17,
                            Valor = 400.50m,
                            Vendedor = "Maria Souza"
                        },
                        new
                        {
                            Id = 18,
                            Valor = 180.20m,
                            Vendedor = "Maria Souza"
                        },
                        new
                        {
                            Id = 19,
                            Valor = 90.75m,
                            Vendedor = "Maria Souza"
                        },
                        new
                        {
                            Id = 20,
                            Valor = 800.50m,
                            Vendedor = "Carlos Oliveira"
                        },
                        new
                        {
                            Id = 21,
                            Valor = 1200.00m,
                            Vendedor = "Carlos Oliveira"
                        },
                        new
                        {
                            Id = 22,
                            Valor = 1950.30m,
                            Vendedor = "Carlos Oliveira"
                        },
                        new
                        {
                            Id = 23,
                            Valor = 1750.80m,
                            Vendedor = "Carlos Oliveira"
                        },
                        new
                        {
                            Id = 24,
                            Valor = 1300.60m,
                            Vendedor = "Carlos Oliveira"
                        },
                        new
                        {
                            Id = 25,
                            Valor = 300.40m,
                            Vendedor = "Carlos Oliveira"
                        },
                        new
                        {
                            Id = 26,
                            Valor = 500.00m,
                            Vendedor = "Carlos Oliveira"
                        },
                        new
                        {
                            Id = 27,
                            Valor = 125.75m,
                            Vendedor = "Carlos Oliveira"
                        },
                        new
                        {
                            Id = 28,
                            Valor = 1000.00m,
                            Vendedor = "Ana Lima"
                        },
                        new
                        {
                            Id = 29,
                            Valor = 1100.50m,
                            Vendedor = "Ana Lima"
                        },
                        new
                        {
                            Id = 30,
                            Valor = 1250.75m,
                            Vendedor = "Ana Lima"
                        },
                        new
                        {
                            Id = 31,
                            Valor = 1400.20m,
                            Vendedor = "Ana Lima"
                        },
                        new
                        {
                            Id = 32,
                            Valor = 1550.90m,
                            Vendedor = "Ana Lima"
                        },
                        new
                        {
                            Id = 33,
                            Valor = 1650.00m,
                            Vendedor = "Ana Lima"
                        },
                        new
                        {
                            Id = 34,
                            Valor = 75.30m,
                            Vendedor = "Ana Lima"
                        },
                        new
                        {
                            Id = 35,
                            Valor = 420.90m,
                            Vendedor = "Ana Lima"
                        },
                        new
                        {
                            Id = 36,
                            Valor = 315.40m,
                            Vendedor = "Ana Lima"
                        });
                });

            modelBuilder.Entity("TesteTarget.Domain.Estoque.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoProduto")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("SaldoApos")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoProduto");

                    b.ToTable("Movimentacao", (string)null);
                });

            modelBuilder.Entity("TesteTarget.Domain.Estoque.Produto", b =>
                {
                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Codigo");

                    b.ToTable("Produto", (string)null);

                    b.HasData(
                        new
                        {
                            Codigo = 101,
                            Descricao = "Caneta Azul",
                            Estoque = 150,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Codigo = 102,
                            Descricao = "Caderno Universitário",
                            Estoque = 75,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Codigo = 103,
                            Descricao = "Borracha Branca",
                            Estoque = 200,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Codigo = 104,
                            Descricao = "Lápis Preto HB",
                            Estoque = 320,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Codigo = 105,
                            Descricao = "Marcador de Texto Amarelo",
                            Estoque = 90,
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("TesteTarget.Domain.Estoque.Movimentacao", b =>
                {
                    b.HasOne("TesteTarget.Domain.Estoque.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("CodigoProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
