// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteTarget.Infrastructure.Data;

#nullable disable

namespace TesteTarget.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003200435_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TesteTarget.Domain.Estoque.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoProduto")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("SaldoApos")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoProduto");

                    b.ToTable("Movimentacao", (string)null);
                });

            modelBuilder.Entity("TesteTarget.Domain.Estoque.Produto", b =>
                {
                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Codigo");

                    b.ToTable("Produto", (string)null);

                    b.HasData(
                        new
                        {
                            Codigo = 101,
                            Descricao = "Caneta Azul",
                            Estoque = 150,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Codigo = 102,
                            Descricao = "Caderno Universitário",
                            Estoque = 75,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Codigo = 103,
                            Descricao = "Borracha Branca",
                            Estoque = 200,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Codigo = 104,
                            Descricao = "Lápis Preto HB",
                            Estoque = 320,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Codigo = 105,
                            Descricao = "Marcador de Texto Amarelo",
                            Estoque = 90,
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("TesteTarget.Domain.Estoque.Movimentacao", b =>
                {
                    b.HasOne("TesteTarget.Domain.Estoque.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("CodigoProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
